repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt -- --check
        language: system
        types:
          - rust
      - id: cargo-clippy
        name: clippy
        entry: cargo clippy -- -D warnings
        language: system
        pass_filenames: false
        types:
          - rust
      - id: cargo-test
        name: cargo test
        entry: cargo test --workspace --all-features
        language: system
        pass_filenames: false
        types_or:
          - rust
      - id: maturin-check
        name: Maturin Check
        entry: maturin develop
        language: system
        pass_filenames: false
        types: [rust]
